#!/bin/sh

while true; do
  #cat /proc/zoneinfo | grep -e nr_free_pages -e count | awk '{s+=$2} END {print s}'
  #cat /proc/zoneinfo | grep count:
  cat /proc/meminfo | grep MemAvailable
  sleep 1
done
